window.ActivityHubI18n.register({
  "YOU'RE THE CHEF!": "きみがシェフ！",
  "Let's make a pizza!": "ピザを作ろう！",
  "Choose a sauce": "ソースを選ぼう",
  "Add your toppings": "トッピングをのせよう",
  "Tap for more. Tap again after ● ● ● to remove.": "タップすると量が増えます。● ● ● のあと、もう一度タップすると取り除けます。",
  "A little of this. A little of that. Your pizza!": "好きなものをのせて、自分だけのピザを作ろう！",
  "Your pizza!": "できあがり！",
  "Making your photo…": "写真を作っています…",
  "Ready to save!": "写真を保存できます！",
  "If the photo opens in a new tab, save it from there.": "写真が別のタブで開いたら、そこから保存してください。",
  "The photo could not be made. Please close this preview and try again.": "写真を作れませんでした。閉じて、もう一度試してください。",
  "Your finished pizza in a white photo frame": "白いフレームに入った、できあがったピザの写真",
  "Pizza cleared to a dry crust. Choose a sauce or no sauce.": "リセットしました。ソースあり・なしを選んでください。",
  "Dry crust. Choose a sauce or no sauce.": "ソースあり・なしを選んでください。",
  "Easy mode.": "かんたんモード。",
  "Hard mode.": "むずかしいモード。",
  "Tap to remove.": "タップして取り除きます。",
  "Tap to add more.": "タップして量を増やします。",
  "none": "なし",
  "light": "少なめ",
  "regular": "ふつう",
  "extra": "多め",
  "removed": "取り除きました",
  "selected.": "選びました。",
  "Play mode": "自由に作るモード",
  "Add one piece, then drag it. Select a piece to edit it. PLAY uses EASY language.": "材料を1つ追加して、ドラッグで動かそう。選ぶと大きさや向きを変えられます。PLAYではかんたんモードになります。",
  "Select a piece": "材料を選ぶ",
  "Edit ingredient": "材料を編集",
  "Smaller": "小さく",
  "Larger": "大きく",
  "Rotate left": "左に回す",
  "Rotate right": "右に回す",
  "Flip": "裏返す",
  "Duplicate": "コピー",
  "Delete": "取り除く",
  "Add one piece.": "1つ追加します。",
  "Play mode. Easy language is on.": "自由に作るモードです。かんたんモードになります。",
  "Learn mode.": "学習モードです。",
  "Creative pizza reset.": "自由に作るピザをリセットしました。",
  "Pizza is full. Remove a piece to add another.": "材料がいっぱいです。取り除いてから追加してください。",
  "About PLAY mode": "PLAYモードの使い方",
  "Close help": "説明を閉じる"
});

window.ActivityHubI18n.register({"Sauce":"ソース","Toppings":"トッピング"});

window.ActivityHubI18n.register({"Previous toppings":"前のトッピング","Next toppings":"次のトッピング"});

window.ActivityHubI18n.register({"Add one piece, then drag it. Pinch with two fingers or use + and − to change its size. PLAY counts small, medium, and big pieces.":"材料を追加して動かそう。2本の指で広げたり縮めたり、＋と−で大きさを変えられます。PLAYではsmall・medium・bigごとに数を数えます。"});
