window.ActivityHubI18n.register({
  "YOU'RE THE CHEF!": "きみがシェフ！",
  "Let's make a pizza!": "ピザを作ろう！",
  "Sauce or no sauce?": "ソースを選ぼう",
  "Add your toppings": "トッピングをのせよう",
  "Tap for more. Tap again after ● ● ● to remove.": "タップすると量が増えます。● ● ● のあと、もう一度タップすると取り除けます。",
  "A little of this. A little of that. Your pizza!": "好きなものをのせて、自分だけのピザを作ろう！",
  "Your pizza!": "できあがり！",
  "Making your photo…": "写真を作っています…",
  "Ready to save!": "写真を保存できます！",
  "If the photo opens in a new tab, save it from there.": "写真が別のタブで開いたら、そこから保存してください。",
  "The photo could not be made. Please close this preview and try again.": "写真を作れませんでした。閉じて、もう一度試してください。",
  "Your finished pizza in a white photo frame": "白いフレームに入った、できあがったピザの写真",
  "Pizza cleared to a dry crust. Choose a sauce or no sauce.": "リセットしました。ソースあり・なしを選んでください。",
  "Dry crust. Choose a sauce or no sauce.": "ソースあり・なしを選んでください。",
  "Easy mode.": "かんたんモード。",
  "Hard mode.": "むずかしいモード。",
  "Tap to remove.": "タップして取り除きます。",
  "Tap to add more.": "タップして量を増やします。",
  "none": "なし",
  "light": "少なめ",
  "regular": "ふつう",
  "extra": "多め",
  "removed": "取り除きました",
  "selected.": "選びました。"
});
